# Generated by Django 4.0.3 on 2022-04-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=48, verbose_name='Πρόσθετες παροχές')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appartment', 'Διαμέρισμα'), ('building', 'Κτήριο'), ('plot', 'Οικόπεδο'), ('detached', 'Μονοκατοικία'), ('maisonette', 'Μεζονέτα')], max_length=24, verbose_name='Είδος')),
                ('floor', models.CharField(choices=[('underground', 'Υπόγειο'), ('semiground', 'Ημιυπόγειο'), ('ground', 'Ισόγειο'), ('semifloor', 'Ημιώροφος'), ('first', '1oς'), ('second', '2oς'), ('third', '3oς'), ('forth', '4oς'), ('fifth', '5oς'), ('sixth', '6oς'), ('seventh', '7oς'), ('plus', '8oς+')], max_length=24, verbose_name='Όροφος')),
                ('area', models.IntegerField(verbose_name='Εμβαδόν (τ.μ)')),
                ('rooms', models.IntegerField(verbose_name='Δωμάτια')),
                ('year_constructed', models.IntegerField(blank=True, null=True, verbose_name='Έτος κατασκευής')),
                ('year_revovated', models.IntegerField(blank=True, null=True, verbose_name='Έτος ανακαίνισης')),
                ('price', models.PositiveIntegerField(verbose_name='Τιμή')),
                ('city', models.CharField(max_length=24, verbose_name='Πόλη')),
                ('address', models.CharField(max_length=24, verbose_name='Οδός')),
                ('number', models.IntegerField(verbose_name='Αριθμός')),
                ('zipcode', models.IntegerField(verbose_name='T.K')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Περιγραφή')),
                ('image', models.ImageField(upload_to='Real_Estate/static/images/')),
                ('district', models.CharField(blank=True, max_length=24, null=True, verbose_name='Περιοχή')),
                ('google_url', models.URLField(blank=True, null=True, verbose_name='google_url')),
                ('more_features', models.ManyToManyField(blank=True, null=True, to='Real_Estate.features', verbose_name='Πρόσθετες παροχές')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Real_Estate/static/images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Real_Estate.house')),
            ],
        ),
    ]
